import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
<div className="">
      <Head>
        <title>Algorithmic Trading</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative">
        <div className="absolute">
          <Image src={'/images/index.jpg'} height={500} width={1535} />
          <article className="text-lg mt-6 text-white md:mx-16 mx-4">
            <p className="">
              Algorithmic trading has exploded in recent years thanks to advancements
              in artificial intelligence and data science. Algorithmic trading 
              allows traders to trade based off information gathered through tools
              like sentiment analysis and satellite footage monitoring. All of 
              which can be interpreted faster though artificial intelligence.
            </p>

            <p>
              As of my first edit to this site, I followed a freecodecamp tutorial
              in algorithmic trading in python to create an equal weight S&P 500 index,
              a momentum based strategy, and a value picking strategy. I expect 
              that as I get more practice with algorithmic trading and learn more
              about programming, data science, and finance, my algorithms will 
              become closer to usable as legitament trading tools.
            </p>
          </article>
        </div>
      </div>
    </div>
  );
}
